const Map<String , String> ar = {
  "mazekty" : "مزيكتي",
  "allSongs" : "كل الاغاني",
  "albums"  : "الالبومات",
  "artists" : "الفنانون",
  "favorite" : "المفضله",
  "details" : "التفاصيل",
  "allDetails" : "كل التفاصيل",
  "name" : "لاسم",
  "artist" : "الفنان",
  "size" : "الحجم",
  "duration" : "المدة",
  "path" : "مسار التخزين",
  "numberOfSongs" :"عدد الاغاني",
  "numberOfAlbums: " : "عدد الالبومات",
  "numberOfSongs: " : "عدد الاغاني",
  "playing" : "يتم تشغيلة",
  "emptyExpression" : "لا يوجد اي ملفات صوت علي جهازك الان",
  "noAlbums" : "لا توجد البومات",
  "noArtists" : "لا يوجد فنانون",
  "pause" : "متوقف مؤقتا",
  "noData" : "قائمة المفضله فارغة" ,
  "selectLanguage" : "تحديد اللغة",
  "notification" : "اشعار جديد",
  "removeFromFavorite" :"تم الازاله من المفضله بنجاح",
  "addToFavorite" :"تمت الاضافة الي المفضله بنجاح",
  "inLoopMode" : "تم تفعيل تكرار ملف الصوت",
  "closeLoopMode" : "تم الغاء وضغ تكرار ملف الصوت"
};